node/src/GraphBuilder.cpp, node/src/GraphBuilder.h, node/src/ops/ReduceMean.cpp, node/src/ops/ReduceMean.h
Add the Op reduceMean on Node.js. It fix 9 failed cases. [Failed Case](https://github.com/webmachinelearning/webnn-polyfill/blob/10e64fae3c722e28ca853008f3c68f7b69b0ea51/test/ops/reduce.js#L249)
=> add the Node.js Op reduceMean

DEPS, examples/BUILD.gn, examples/MobileNetV2/README.md, examples/ResNet/Main.cpp, examples/ResNet/README.md, examples/ResNet/ResNet.cpp, examples/ResNet/ResNet.h, examples/SqueezeNet/SqueezeNet.cpp, examples/SqueezeNet/SqueezeNet.h, node/examples/electron/image_classification/package-lock.json, node/examples/electron/lenet/package-lock.json, node/package-lock.json, node/src/GraphBuilder.cpp, node/src/GraphBuilder.h, node/src/Utils.h, node/src/ops/Pad.cpp, node/src/ops/Pad.h, node/src/ops/ReduceMean.cpp, src/tests/BUILD.gn, src/tests/end2end/models/ResNetNchw.cpp, src/tests/end2end/models/ResNetNhwc.cpp, src/webnn_native/dml/GraphDML.cpp, src/webnn_native/ops/Conv2d.cpp
PTAL, thanks! @fujunwei 
Now ResNet NHWC/NCHW can both pass on Linux/Windows as C++ or electron examples. All model tests can pass except on Windows DML backend, the related issue is #23.
=> Support ResNet nchw/nhwc and refactor some codes

README.md, third_party/openvino/ienn/README.md, third_party/openvino/ienn/build_ienn.py, third_party/openvino/ienn/src/ie_compilation.cpp, third_party/openvino/ienn/src/ie_compilation.h, third_party/openvino/ienn/src/ie_nn_c_api.cpp
This PR will fix #18 and #20.
With this PR merged, we also need to install openvino 2021.4 to set up our environment. PTAL, thanks! @fujunwei
=> Refactor IE codes and upgrade OpenVINO to 2021.4

src/tests/BUILD.gn, src/tests/end2end/SigmoidTests.cpp, src/webnn_native/GraphBuilder.cpp, src/webnn_native/GraphBuilder.h, src/webnn_native/dml/GraphDML.cpp, src/webnn_native/openvino/GraphIE.cpp, src/webnn_native/ops/Unary.h, third_party/openvino/ienn/src/ie_model.cpp, third_party/openvino/ienn/src/ie_model.h, third_party/openvino/ienn/src/ie_nn_c_api.cpp, third_party/openvino/ienn/src/ie_nn_c_api.h, webnn.json
I have tested IE on Linux and DML on Windows.
@fujunwei @mingmingtasd PTAL, thanks.
=> Support Sigmoid for IE/DML

.github/workflows/build_test_dml.yml, .github/workflows/build_test_null.yml, README.md, workflow_scripts/package.json, workflow_scripts/src/ci.js
=> Add CI to build and test null and DML backend.

src/tests/BUILD.gn, src/tests/end2end/ResampleTests.cpp, src/webnn_native/BUILD.gn, src/webnn_native/Graph.cpp, src/webnn_native/Graph.h, src/webnn_native/GraphBuilder.cpp, src/webnn_native/GraphBuilder.h, src/webnn_native/dml/GraphDML.cpp, src/webnn_native/dml/GraphDML.h, src/webnn_native/openvino/GraphIE.cpp, src/webnn_native/openvino/GraphIE.h, src/webnn_native/ops/Resample.cpp, src/webnn_native/ops/Resample.h, third_party/openvino/ienn/src/ie_model.cpp, third_party/openvino/ienn/src/ie_model.h, third_party/openvino/ienn/src/ie_nn_c_api.cpp, third_party/openvino/ienn/src/ie_nn_c_api.h, webnn.json
-  linux:
out/ie/webnn_end2end_tests --gtest_filter=ResampleTests.*
Note: Google Test filter = ResampleTests.*
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from ResampleTests
[ RUN      ] ResampleTests.UpsampleLinear
[       OK ] ResampleTests.UpsampleLinear (15 ms)
[ RUN      ] ResampleTests.UpsampleNearest
[       OK ] ResampleTests.UpsampleNearest (10 ms)
[----------] 2 tests from ResampleTests (25 ms total)
[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (25 ms total)
[  PASSED  ] 2 tests.
- Windows
out\dml\webnn_end2end_tests
.exe --gtest_filter=ResampleTests.*
Note: Google Test filter = ResampleTests.*
[==========] Running 2 tests from 1 test suite.
[----------] Global …
=> [IE/DML]Implement resample

README.md
@huningxin Now CI badges are on top of REAME.md, PTAL, thanks.
=> Update CI badges.

src/tests/BUILD.gn, src/tests/end2end/TanhTests.cpp, src/webnn_native/GraphBuilder.cpp, src/webnn_native/GraphBuilder.h, src/webnn_native/dml/GraphDML.cpp, src/webnn_native/openvino/GraphIE.cpp, src/webnn_native/ops/Unary.h, third_party/openvino/ienn/src/ie_model.cpp, third_party/openvino/ienn/src/ie_model.h, third_party/openvino/ienn/src/ie_nn_c_api.cpp, third_party/openvino/ienn/src/ie_nn_c_api.h, webnn.json
@fujunwei @mingmingtasd PTAL, thanks!
Test results:
**[IE]** webnn_end2end_tests --gtest_filter=Tanh*
Note: Google Test filter = Tanh*
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from TanhTests
[ RUN      ] TanhTests.TanhWith1DTensor
[       OK ] TanhTests.TanhWith1DTensor (10 ms)
[ RUN      ] TanhTests.TanhWith3DTensor
[       OK ] TanhTests.TanhWith3DTensor (5 ms)
[----------] 2 tests from TanhTests (16 ms total)
[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (16 ms total)
[  PASSED  ] 2 tests.
**[DML]** webnn_end2end_tests.exe --gtest_filter=Tanh*
Note: Google Test filter = Tanh*
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up. …
=> Support Tanh for IE/DML

src/webnn_native/ops/Constant.h, third_party/openvino/ienn/src/ie_model.h, third_party/openvino/ienn/src/ie_nn_c_api.cpp, third_party/openvino/ienn/src/ie_nn_c_api.h
@huningxin @fujunwei PTAL, thanks.
=> Fix format issue.

examples/MobileNetV2/Main.cpp, examples/MobileNetV2/MobileNetV2.cpp, examples/MobileNetV2/MobileNetV2.h, examples/MobileNetV2/README.md, examples/ResNet/Main.cpp, examples/ResNet/README.md, examples/ResNet/ResNet.cpp, examples/ResNet/ResNet.h, examples/SampleUtils.cpp, examples/SampleUtils.h, examples/SqueezeNet/Main.cpp, examples/SqueezeNet/README.md, examples/SqueezeNet/SqueezeNet.cpp, examples/SqueezeNet/SqueezeNet.h, src/tests/end2end/models/MobileNetV2BatchNormNchw.cpp, src/tests/end2end/models/MobileNetV2Nchw.cpp, src/tests/end2end/models/MobileNetV2Nhwc.cpp, src/tests/end2end/models/ResNetNchw.cpp, src/tests/end2end/models/ResNetNhwc.cpp, src/tests/end2end/models/SqueezeNetNchw.cpp, src/tests/end2end/models/SqueezeNetNhwc.cpp
This PR includes these features:
1. Re-define compilation time, remove the time spent on loading models from it.
2. Add first inference for warming up when setting nIter>1 for performance measurement.
3. Refactor and simplify codes for supporting other image classification examples more easily in the future.
All examples and model tests can pass. PTAL, thanks! @fujunwei
=> Refactor C++ examples codes

node/src/Graph.cpp, node/src/GraphBuilder.cpp, node/src/GraphBuilder.h, node/src/Utils.h, node/src/ops/BatchNorm.cpp, node/src/ops/Concat.cpp, node/src/ops/Constant.cpp, node/src/ops/Conv2d.cpp, node/src/ops/Gemm.cpp, node/src/ops/Input.cpp, node/src/ops/LeakyRelu.cpp, node/src/ops/Pad.cpp, node/src/ops/Pool2d.cpp, node/src/ops/ReduceMean.cpp, node/src/ops/Resample.cpp, node/src/ops/Resample.h, node/src/ops/Reshape.cpp, node/src/ops/Transpose.cpp
All webnn-polyfill tests of resample pass. PTAL,thanks! @huningxin
```
test resample
✓ resample upsample scales linear
✓ resample upsample sizes linear
✓ resample upsample scales nearest
✓ resample upsample sizes nearest
4 passing (21ms)
```
=> Add node.js binding for Resample op

generator/webnn_json_generator.py, src/webnn_native/Operator.h, webnn.json
=> Add operator into webnn.json and fix generator issue

node/src/Context.cpp
Support the devicePreference for `MLContext`.
=> Support the devicePreference

node/src/GraphBuilder.cpp, node/src/GraphBuilder.h
=> [Node] add the Op div

node/src/GraphBuilder.cpp, node/src/GraphBuilder.h, node/src/ops/InstanceNorm.cpp, node/src/ops/InstanceNorm.h
Add Op InstanceNorm for Node node binding.
=> [Node] add the Op InstanceNorm

.github/workflows/build_test_node_dml.yml, README.md, workflow_scripts/regression_check.py
Please have a preview on CI failure for node binding sample: https://github.com/BruceDai/webnn-native/runs/3318156014.
And add a new badge of CI for node binding, if CI for node binding passed, the badge is ![Node Binding (DirectML backend)](https://github.com/BruceDai/webnn-native/actions/workflows/build_test_node_dml.yml/badge.svg)
=> Add CI for Node Binding with WebNN native by DirectML backend.

examples/SampleUtils.cpp, node/src/Context.cpp, src/tests/End2EndTestsMain.cpp, src/webnn_native/dml/GraphDML.cpp, src/webnn_native/openvino/GraphIE.cpp
=> Fix issue of node.js binding for ContextOptions

src/webnn_native/dml/GraphDML.cpp
fix https://github.com/webmachinelearning/webnn-native/issues/73 and https://github.com/webmachinelearning/webnn-native/issues/78.
=> [DML] Support Max and Min operations

node/src/GraphBuilder.cpp, node/src/GraphBuilder.h, src/tests/BUILD.gn, src/tests/end2end/PowTests.cpp, src/webnn_native/GraphBuilder.cpp, src/webnn_native/GraphBuilder.h, src/webnn_native/openvino/GraphIE.cpp, src/webnn_native/ops/Binary.h, webnn.json
The implementation based on IE for Op pow and its Node.js binding. The screenshots for Node.js tests is here:
=> [IE] add Op Pow and its node.js binding

.github/workflows/build_test_node_openvino_linux.yml, README.md
The new badge is ![Node Binding (OpenVINO backend / Linux)](https://github.com/BruceDai/webnn-native/actions/workflows/build_test_node_openvino_linux.yml/badge.svg).
=> Add CI for Node Binding with WebNN native by OpenVINO backend on Linux platform.

.github/workflows/build_test_openvino_windows.yml, README.md
Please have a preview on the [link](https://github.com/BruceDai/webnn-native/runs/3377624236?check_suite_focus=true).
This new badge is ![OpenVINO backend (Windows)](https://github.com/BruceDai/webnn-native/actions/workflows/build_test_openvino_windows.yml/badge.svg).
=> Add CI for OpenVINO backend on Windows platform.

examples/MobileNetV2/MobileNetV2.cpp, examples/MobileNetV2/MobileNetV2.h, examples/ResNet/ResNet.cpp, examples/SampleUtils.h, examples/SqueezeNet/SqueezeNet.cpp, src/tests/end2end/models/MobileNetV2BatchNormNchw.cpp, src/tests/end2end/models/MobileNetV2Nchw.cpp, src/tests/end2end/models/MobileNetV2Nhwc.cpp, src/tests/end2end/models/ResNetNchw.cpp, src/tests/end2end/models/ResNetNhwc.cpp, src/tests/end2end/models/SqueezeNetNchw.cpp, src/tests/end2end/models/SqueezeNetNhwc.cpp, src/webnn_native/ops/BatchNorm.cpp, src/webnn_native/ops/BatchNorm.h, src/webnn_native/ops/Conv2d.cpp, src/webnn_native/ops/Conv2d.h
This PR supported fused C++ examples by default. I also added model tests for fused models. PTAL, thanks! @fujunwei @huningxin
=> Support fused C++ examples

examples/MobileNetV2/MobileNetV2.cpp, examples/ResNet/ResNet.cpp, examples/SqueezeNet/SqueezeNet.cpp, src/tests/end2end/models/MobileNetV2BatchNormNchw.cpp, src/tests/end2end/models/MobileNetV2Nchw.cpp, src/tests/end2end/models/MobileNetV2Nhwc.cpp, src/tests/end2end/models/ResNetNchw.cpp, src/tests/end2end/models/ResNetNhwc.cpp, src/tests/end2end/models/SqueezeNetNchw.cpp, src/tests/end2end/models/SqueezeNetNhwc.cpp
=> Refactor fused examples and model tests

node/src/Utils.h
fix #115
reopen #106 
@fujunwei PTAL. cc @Honry
=> [Node] Revert the SharedArrayBuffer support

DEPS, examples/MobileNetV2/MobileNetV2.cpp, examples/SampleUtils.cpp, generator/templates/webnn_cpp.h, node/src/ops/Clamp.cpp, src/tests/end2end/ClampTests.cpp, src/tests/end2end/Conv2dTests.cpp, src/webnn_native/GraphBuilder.cpp, src/webnn_native/dml/GraphDML.cpp, src/webnn_native/dml/GraphDML.h, src/webnn_native/openvino/GraphIE.cpp, src/webnn_native/ops/Clamp.h, webnn.json
=> Re-implement clamp to use float min/max

third_party/openvino/ngraph_c_api/src/ngraph_c_api.cpp
To fix #109 . PTAL, thanks! @fujunwei
=> Fix build warnings of ngraph_c_api

node/src/ops/Conv2d.cpp
The PR can pass the  `Transpose` related `Conv2d` test cases as those are passed in native tests.
=> [Node] add Transpose Options for Conv2d

examples/SampleUtils.h, src/tests/BUILD.gn, src/tests/end2end/SliceTests.cpp, src/webnn_native/Graph.cpp, src/webnn_native/Graph.h, src/webnn_native/GraphBuilder.cpp, src/webnn_native/GraphBuilder.h, src/webnn_native/openvino/GraphIE.cpp, src/webnn_native/openvino/GraphIE.h, src/webnn_native/ops/Slice.h, third_party/openvino/ngraph_c_api/src/ngraph_c_api.cpp, third_party/openvino/ngraph_c_api/src/ngraph_c_api.h, webnn.json
Add Op Slice based on the openVINO backend. The DML backend is not implemented in this PR. The `SlicesOptions` will be supported soon.
=> [IE] Kunliang/add slice

node/src/GraphBuilder.cpp, node/src/GraphBuilder.h
I have added the Op `hardSwish` on Node.js. But it seems that there is no tests for it, so I can not verify it on Node.js.
=> add the Op hardSwish on Node.js

node/src/GraphBuilder.cpp, node/src/GraphBuilder.h, node/src/ops/Squeeze.cpp, node/src/ops/Squeeze.h
Add the Op Squeeze on Node.js. Related test cases are passed.
=> add Op Squeeze on Node.js

node/src/GraphBuilder.cpp, node/src/GraphBuilder.h, node/src/ops/Slice.cpp, node/src/ops/Slice.h
Add the Op Slice to the Node.js. And fix a error in Op Squeeze. The `slice`-related test cases are passed.
=> [Node] add Op Slice and fix a error in Op Squeeze

DEPS
@fujunwei @Honry PTAL, thanks.
=> Updated DEPS for Style Transer example.

.github/workflows/build_test_onednn_linux.yml, .github/workflows/build_test_onednn_windows.yml, README.md
@huningxin @fujunwei PTAL, thanks.
=> [CI] Enable oneDNN backend.

DEPS, src/webnn_native/dml/deps/src/device.cpp, src/webnn_native/dml/deps/src/device.h
=> Roll third_party/gpgmm/ d370f29db..7c81fae56 (114 commits)

.gitignore, DEPS, NOTICE, README.md, build_overrides/webnn_features.gni, src/common/BUILD.gn, src/webnn_native/BUILD.gn, src/webnn_native/Instance.cpp, src/webnn_native/Operand.h, src/webnn_native/WebnnNative.cpp, src/webnn_native/mlas/BackendMLAS.cpp, src/webnn_native/mlas/BackendMLAS.h, src/webnn_native/mlas/ContextMLAS.cpp, src/webnn_native/mlas/ContextMLAS.h, src/webnn_native/mlas/GraphMLAS.cpp, src/webnn_native/mlas/GraphMLAS.h, webnn.json
=> Support MLAS backend

examples/SampleUtils.h, src/tests/end2end/Pool2dTests.cpp, src/webnn_native/openvino/GraphIE.cpp, src/webnn_native/ops/Pool2d.cpp, src/webnn_native/ops/Pool2d.h, third_party/openvino/ngraph_c_api/src/ngraph_c_api.cpp, third_party/openvino/ngraph_c_api/src/ngraph_c_api.h, webnn.json
PTAL, thanks! @fujunwei @huningxin  I also raised an issue #184 on DML for some un-supported cases.
=> Support roundingType and outputSizes for pool2d on OV/DML

DEPS, examples/MobileNetV2/MobileNetV2.cpp, examples/ResNet/ResNet.cpp, examples/SampleUtils.h, examples/SqueezeNet/SqueezeNet.cpp, node/src/GraphBuilder.cpp, node/src/GraphBuilder.h, node/src/Utils.h, node/src/ops/Conv2d.cpp, node/src/ops/Conv2d.h, src/tests/BUILD.gn, src/tests/end2end/Conv2dTests.cpp, src/tests/end2end/ConvTranspose2dTests.cpp, src/webnn_native/BUILD.gn, src/webnn_native/Graph.cpp, src/webnn_native/Graph.h, src/webnn_native/GraphBuilder.cpp, src/webnn_native/GraphBuilder.h, src/webnn_native/Utils.cpp, src/webnn_native/Utils.h, src/webnn_native/dml/GraphDML.cpp, src/webnn_native/dml/GraphDML.h, src/webnn_native/onednn/GraphDNNL.cpp, src/webnn_native/openvino/GraphIE.cpp, src/webnn_native/openvino/GraphIE.h, src/webnn_native/ops/Conv2d.cpp, src/webnn_native/ops/Conv2d.h, src/webnn_native/ops/ConvTranspose2d.cpp, webnn.json
Split conv2d to conv2d and convTranspose2d. @fujunwei PTAL, thanks.
=> [IE/DML] Split conv2d to conv2d and convTranspose2d.

examples/MobileNetV2/README.md, examples/ResNet/README.md, examples/SqueezeNet/README.md
PTAl, thanks! Also added a [wiki](https://github.com/webmachinelearning/webnn-native/wiki/How-to-select-a-preferred-kind-of-gpu-to-infer-on%3F). @fujunwei
=> Update readme for selecting iGPU/dGPU

.github/workflows/build_test_dml.yml, .github/workflows/build_test_node_dml.yml, .github/workflows/build_test_node_openvino_windows.yml, .github/workflows/build_test_null.yml, .github/workflows/build_test_onednn_windows.yml, .github/workflows/build_test_openvino_windows.yml
fix #209 
@fujunwei @miaobin @mingmingtasd PTAL, thanks.
=> Use Windows Server 2019 environment for CI on Windows platform.

examples/MobileNetV2/README.md, examples/ResNet/README.md, examples/SampleUtils.cpp, examples/SqueezeNet/README.md
PTAL, thanks! @BruceDai @fujunwei
=> Fix the typo issue in readme

src/webnn_native/mlas/ContextMLAS.cpp, src/webnn_native/mlas/ContextMLAS.h, src/webnn_native/mlas/GraphMLAS.cpp
=> [MLAS] fix the build issue

src/tests/BUILD.gn, src/tests/unittests/native/ContextMockTests.cpp, src/tests/unittests/native/GraphMockTests.cpp, src/tests/unittests/native/mocks/ContextMock.h, src/tests/unittests/native/mocks/GraphMock.h, src/webnn_native/Graph.cpp, src/webnn_native/Graph.h, src/webnn_native/null/ContextNull.cpp, src/webnn_native/null/ContextNull.h
Supported some mock tests under unit tests for base objects as below:
=> Support gMock tests

src/webnn_native/dml/GraphDML.cpp
When the code runs to `CreateOperatorNode` on DML backend It will be crashed. 
@mingmingtasd @fujunwei Could you help me find where is the problem? Thanks a lot!
=> Support Gru on DML backend

src/webnn_native/dml/GraphDML.cpp, src/webnn_native/openvino/GraphIE.cpp
Fix #218 . Fix the crash issue and for some test cases, others have been tracked in known issues.
PTAL, thanks! @fujunwei
=> Fix Gemm issues on debug version

src/tests/end2end/ConcatTests.cpp
Fix #224, PTAL, thanks! @BruceDai @fujunwei
=> Add more end2end tests for concat op with input num > 2

DEPS, src/webnn_native/dml/GraphDML.cpp, src/webnn_native/ops/Pool2d.cpp, src/webnn_native/ops/Pool2d.h
1. Update DirectMLX to the latest
2. Support roundingType/ outputSizes for pool2d
PTAL, thanks! @fujunwei
=> Update DirectMLX.h to enhance support for pool2d

src/webnn_native/GraphBuilder.cpp, src/webnn_native/GraphBuilder.h, src/webnn_native/Operand.h, src/webnn_native/ops/Constant.h
fix https://github.com/otcshare/webnn-native/issues/1011
=> Break reference between Operand and Operater

src/webnn_native/xnnpack/GraphXNN.cpp
Release XNNPACK runtime and subgraph correctly.
No memory leak is detected for webnn_end2end_tests after applying this PR.
@fujunwei , @BruceDai PTAL.
=> [XNNPACK] fix memory leak

.github/workflows/memory_leak_check_dml.yml, README.md, workflow_scripts/memory_leak_check.py
Preview of this CI with having memory leak: https://github.com/BruceDai/webnn-native/runs/6361913879?check_suite_focus=true
@fujunwei PTAL, thanks.
=> Add memory leak check CI for DirectML backend.

src/webnn/native/xnnpack/BackendXNN.cpp, src/webnn/native/xnnpack/BackendXNN.h
=> Fix a error caused by refactor

.github/workflows/build_test_xnnpack_linux.yml, .github/workflows/build_test_xnnpack_windows.yml, README.md
=> Add CI for testing WebNN XNNPACK backend on both Windows and Linux platforms

examples/MobileNetV2/Main.cpp, examples/MobileNetV2/MobileNetV2.cpp, examples/MobileNetV2/MobileNetV2.h, examples/ResNet/Main.cpp, examples/ResNet/README.md, examples/ResNet/ResNet.cpp, examples/ResNet/ResNet.h, examples/SqueezeNet/Main.cpp, examples/SqueezeNet/SqueezeNet.cpp, examples/SqueezeNet/SqueezeNet.h, src/webnn/tests/end2end/models/MobileNetV2BatchNormNchw.cpp, src/webnn/tests/end2end/models/MobileNetV2Nchw.cpp, src/webnn/tests/end2end/models/MobileNetV2Nhwc.cpp, src/webnn/tests/end2end/models/ResNetNchw.cpp, src/webnn/tests/end2end/models/ResNetNhwc.cpp, src/webnn/tests/end2end/models/SqueezeNetNchw.cpp, src/webnn/tests/end2end/models/SqueezeNetNhwc.cpp
PTAL, thanks! @fujunwei @BruceDai
=> Add ResNet50V2 Nhwc model tests

build_overrides/webnn_features.gni, src/webnn/common/BUILD.gn, src/webnn/native/BUILD.gn, src/webnn/native/Instance.cpp, src/webnn/native/nnapi/BackendNnapi.cpp, src/webnn/native/nnapi/BackendNnapi.h, src/webnn/native/nnapi/ContextNnapi.cpp, src/webnn/native/nnapi/ContextNnapi.h, src/webnn/native/nnapi/ErrorNnapi.cpp, src/webnn/native/nnapi/ErrorNnapi.h, src/webnn/native/nnapi/GraphNnapi.cpp, src/webnn/native/nnapi/GraphNnapi.h, src/webnn/native/nnapi/NeuralNetworksTypes.h, src/webnn/native/nnapi/NnapiManager.cpp, src/webnn/native/nnapi/NnapiManager.h, src/webnn/native/nnapi/NnapiUtils.h, src/webnn/native/nnapi/nnapi_implementation.cc, src/webnn/native/nnapi/nnapi_implementation.h, webnn.json
- Adds Sigmoid and Convolution op support
=> Add NNAPI backend support

src/webnn/tests/end2end/Pool2dTests.cpp
PTAL, thanks! @BruceDai @fujunwei
=> Disable test cases of l2pool2d

src/webnn/native/BUILD.gn, src/webnn/native/dml/DMLUtils.cpp, src/webnn/native/dml/DMLUtils.h, src/webnn/native/dml/GraphDML.cpp, src/webnn/native/dml/GraphDML.h
Refactor and optimize the DML backend, will also update design doc later to align with this PR.
=> Refactor the DML backend

src/webnn/native/dml/GraphDML.cpp
Support convTranspose2d op for DML backend. @mingmingtasd @fujunwei PTAL, thanks!
=> [DML] Add convTranspose2d op for DML backend

src/webnn/native/nnapi/GraphNnapi.h
Signed-Off-by: Vijeetkumar Benni <vijeetkumar.benni@intel.com>
=>  (nnapi)  Added support for zero input dimension for Gemm op

src/webnn/native/dml/GraphDML.cpp, src/webnn/native/dml/GraphDML.h
Support gru op for DML backend. @mingmingtasd @fujunwei PTAL, thanks!
=> [DML] Add gru op for DML backend

examples/SampleUtils.cpp
PTAL, thanks! @fujunwei @bbernhar
=> Fix dml/dmlx memory leaks for C++ examples

DEPS, src/webnn/native/dmlx/deps/src/device.cpp, src/webnn/native/dmlx/deps/src/device.h
* Changes to update GPGMM to v0.0.4
* Fixed bug in DML backend where descriptor heap size was incorrect.
=> Roll third_party/gpgmm/ 72f910e8d..61fcfcbd8 (143 commits)

examples/MobileNetV2/MobileNetV2.cpp, examples/MobileNetV2/MobileNetV2.h, examples/ResNet/ResNet.cpp, examples/ResNet/ResNet.h, examples/SampleUtils.cpp, examples/SampleUtils.h, examples/SqueezeNet/SqueezeNet.cpp, examples/SqueezeNet/SqueezeNet.h, examples/SuperResolution/SuperResolution.cpp, examples/SuperResolution/SuperResolution.h
=> Refactor C++ examples

DEPS, src/webnn/native/dmlx/deps/src/device.cpp, src/webnn/native/dmlx/deps/src/device.h, src/webnn/native/dmlx/deps/src/util.h
* Depreciate ResidencySet with ResidencyList.
* Depreciate Heap::As with ComPtr:As.
@fujunwei Please merge when ready.
=> Roll GPGMM

src/webnn/native/Instance.cpp
=> Disable dml flag in Instance .cpp

.github/workflows/auto_roll_deps_dml.yml, .github/workflows/auto_roll_deps_mlas.yml, .github/workflows/auto_roll_deps_onednn.yml, .github/workflows/auto_roll_deps_test.yml, .github/workflows/auto_roll_deps_xnnpack.yml
This PR is to split whole Auto Roll DEPS CI into sub CIs, thus we could merger those latest update of decencies which're checked PASS, and go to fix those latest update of decencies which're checked FAIL.
@fujunwei PTAL, thanks.
=> Split Auto Roll DEPS CI into sub CIs.

.github/workflows/auto_roll_deps_dml.yml, .github/workflows/auto_roll_deps_mlas.yml, .github/workflows/auto_roll_deps_onednn.yml, .github/workflows/auto_roll_deps_test.yml, .github/workflows/auto_roll_deps_xnnpack.yml, .gitignore
=> Optimize Auto roll CIs by updating PR's title and scheduling time.
