webmachinelearning/webnn-native

- README.md
Developers need to set DEPOT_TOOLS_WIN_TOOLCHAIN=0
> Fix depot_tools installation steps for Windows

- node/src/Utils.h
- node/src/ops/Constant.cpp
This PR aims to solve the failed case for `uilder.constant should throw for invalid value according to type`.
> add the check for Constants of the type Uint32, Int8, Uint8

- src/tests/BUILD.gn
- src/webnn_native/dml/GraphDML.cpp
- third_party/openvino/ienn/src/ie_model.cpp
- Linux
out/ie/webnn_end2end_tests --gtest_filter=SubTests.*
Note: Google Test filter = SubTests.*
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from SubTests
[ RUN      ] SubTests.SubTwoInputs
[       OK ] SubTests.SubTwoInputs (8 ms)
[ RUN      ] SubTests.SubBroadcast
[       OK ] SubTests.SubBroadcast (4 ms)
[----------] 2 tests from SubTests (12 ms total)
[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (12 ms total)
[  PASSED  ] 2 tests.
- Windows
out\dml\webnn_end2end_tests
.exe --gtest_filter=SubTests.*
Note: Google Test filter = SubTests.*
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from SubTests
[ RUN …
> [IE\DML]Implement sub op

- .github/workflows/clang_format_check.yml
- README.md
- workflow_scripts/clang_format_check.sh
Please have a preview on format failure sample: https://github.com/BruceDai/webnn-native/runs/3141300499.
And add a new badge for clang format, if format checking passed, the badge is ![clang format](https://github.com/BruceDai/webnn-native/actions/workflows/clang_format_check.yml/badge.svg)
> Add clang format checking into CI.

- src/tests/BUILD.gn
- src/tests/end2end/InstanceNormTests.cpp
- src/webnn_native/BUILD.gn
- src/webnn_native/Graph.cpp
- src/webnn_native/Graph.h
- src/webnn_native/GraphBuilder.cpp
- src/webnn_native/GraphBuilder.h
- src/webnn_native/dml/GraphDML.cpp
- src/webnn_native/dml/GraphDML.h
- src/webnn_native/openvino/GraphIE.cpp
- src/webnn_native/openvino/GraphIE.h
- src/webnn_native/ops/InstanceNorm.cpp
- src/webnn_native/ops/InstanceNorm.h
- third_party/openvino/ienn/src/ie_model.cpp
- third_party/openvino/ienn/src/ie_model.h
- third_party/openvino/ienn/src/ie_nn_c_api.cpp
- third_party/openvino/ienn/src/ie_nn_c_api.h
- webnn.json
Transferred from @lisa0314 and fixed the issue of IC failure.
Thanks for Mingming's help. @fujunwei @mingmingtasd PTAL, thanks!
Test result:
**[IE]** webnn_end2end_tests --gtest_filter=InstanceNorm*
Note: Google Test filter = InstanceNorm*
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from InstanceNormTests
[ RUN      ] InstanceNormTests.InstanceNormNchw
[       OK ] InstanceNormTests.InstanceNormNchw (28 ms)
[ RUN      ] InstanceNormTests.InstanceNormNhwc
[       OK ] InstanceNormTests.InstanceNormNhwc (26 ms)
[ RUN      ] InstanceNormTests.InstanceNormWithEpsilon
[       OK ] InstanceNormTests.InstanceNormWithEpsilon (4 ms)
[----------] 3 tests from InstanceNormTests (58 ms total)
[----------] Global test environment …
> [IE/DML]Implement InstanceNorm

- examples/MobileNetV2/Main.cpp
- examples/MobileNetV2/README.md
- examples/ResNet/Main.cpp
- examples/ResNet/README.md
- examples/SampleUtils.cpp
- examples/SampleUtils.h
- examples/SqueezeNet/Main.cpp
- examples/SqueezeNet/README.md
- src/tests/End2EndTestsMain.cpp
Now we can run C++ examples on a target device by -d cpu/gpu/default. PTAL, thanks! @huningxin
> Support device selection for C++ examples with -d option

- node/src/Context.cpp
- node/src/ML.cpp
Add the `powerPreference` option for Context. It resolves the two failed cases [failed case 1](https://github.com/webmachinelearning/webnn-polyfill/blob/7d33b3c62918cd4dab1753446086c9d3261b691a/test/api/context.js#L36)  and [failed case 2](https://github.com/webmachinelearning/webnn-polyfill/blob/7d33b3c62918cd4dab1753446086c9d3261b691a/test/api/context.js#L40).
> add the powerPreference for CreateContext for node binding

- third_party/openvino/ngraph_c_api/build_ngraph_c_api_unix.sh
On the Linux environment, the `libinference_engine_c_api.so` in openvino can not be moved to the target path successfully. This PR fixes the corresponding error.
> Fix the build error on Linux

- src/common/BUILD.gn
Include paths in `src/test` are being specified from WebNN's root directory (ex. `src/examples`, `src/third_party`, etc) which means we must also specify `${webnn_root}` in the common `BUILD.gn` config to build tests under third_party.
> Missing include for building tests

- node/package.json
With this command "npm run report", test will generate test report file 'result.xml' which would help regression check by running coming CI for node test.
@huningxin @fujunwei PTAL, thanks.
> Updated node/package.json by adding "npm run report"

- src/webnn_native/BUILD.gn
All build paths under `\\third_party` should be relative to `webnn_root`. Otherwise, `webnn_native` cannot be built under `\\third_party`.
> Fix BUILD paths to third_party

- .github/workflows/build_test_openvino_linux.yml
- README.md
This PR is for CI checking OpenVINO backend with OpenVINO Toolkit of version 2021.4.582 on Linux platform.
The new badge is ![OpenVINO backend (Linux)](https://github.com/BruceDai/webnn-native/actions/workflows/build_test_openvino_linux.yml/badge.svg).
> Add CI for testing OpenVINO backend on Linux platform.

- .github/workflows/build_test_dml.yml
- .github/workflows/build_test_node_dml.yml
- README.md
Here're updated badges:
I suggest you could merge this one first, after this pr launched, I will continue to fix conflict for #91 with removing last empty commit, thanks.
> Updated two badges for DirectML backend with explicit "Windows" characters.

- generator/templates/webnn_native/webnn_structs.h
- webnn.json
fix #61
The generated `webnn_structs_autogen.h` sets nullptr to optional object pointer:
```c++
struct BatchNormOptions {
OperandBase* scale = nullptr;
OperandBase* bias = nullptr;
uint32_t axis = 1;
float epsilon = 1e-05;
OperatorBase* activation = nullptr;
};
struct ClampOptions {
OperandBase* minValue = nullptr;
OperandBase* maxValue = nullptr;
};
struct Conv2dOptions {
uint32_t paddingCount = 0;
int32_t const * padding = nullptr;
uint32_t stridesCount = 0;
int32_t const * strides = nullptr;
uint32_t dilationsCount = 0;
int32_t const * dilations = nullptr;
ml::AutoPad autoPad = ml::AutoPad::Explicit;
int32_t groups = 1;
ml::InputOperandLayout inputLayout = ml::InputOperandLayout::Nchw;
ml::FilterOperandLayout filterLayout = ml::FilterOperandLayout::Oihw;
OperandBase* bias = nullptr; …
```
> Support optional object in webnn.json

- workflow_scripts/test_by_openvino_windows.bat
This PR is to add a bash script with a workaround of OpenVINO environment setup for testing OpenVINO backend on Windows since OpenVINO environment couldn't be setup by GitHub Actions's step of running OpenVINO **setupvar.bat** directly likes:
```yaml
- name: Setup OpenVINO environment
shell: cmd
run: |
"C:\Program Files (x86)\Intel\openvino_2021\bin\setupvars.bat"
```
> Add bash script for testing by OpenVINO backend on Windows.

- .github/workflows/build_test_node_openvino_windows.yml
- README.md
Please have a preview on the [link](https://github.com/BruceDai/webnn-native/runs/3408450764?check_suite_focus=true).
This new badge is ![Node Binding (OpenVINO backend / Windows)](https://github.com/BruceDai/webnn-native/actions/workflows/build_test_node_openvino_windows.yml/badge.svg).
> Add CI for Node Binding with WebNN native by OpenVINO backend on Windows platform.

- src/webnn_native/dml/deps/src/device.cpp
DML feature level 3 is required so this change requires the
DML device to support it or fail.
@huningxin @fujunwei
> Require DML feature level when creating DML device.

- src/webnn_native/BUILD.gn
Building the WebNN E2E test target will fail to run because of the missing DML DLL binary in the output build directory that is only copied when the whole project gets built. To fix, the DirectML.dll dependency is specified as a data_deps for the webnn_native_sources build target.
This fix should also resolve https://github.com/webmachinelearning/webnn-native/issues/124 once merged.
@fujunwei @huningxin
> Fix WebNN test only builds due to missing DirectML.dll.

- node/src/GraphBuilder.cpp
- node/src/GraphBuilder.h
- node/src/ops/Split.cpp
- node/src/ops/Split.h
The Op Split is added in Node.js Version. And related test cases are passed. However, I am not sure if I should create `OperandArray.h` and `OperandArray.cpp`, though I do not think such class plays an important role for the Node.js version. Could you share your ideas ?
> [Node] Add the Op Split

- src/tests/BUILD.gn
- src/tests/end2end/models/MobileNetV2BatchNormNchw.cpp
- src/tests/end2end/models/MobileNetV2Nchw.cpp
- src/tests/end2end/models/MobileNetV2Nhwc.cpp
- src/tests/end2end/models/ResNetNchw.cpp
- src/tests/end2end/models/ResNetNhwc.cpp
- src/tests/end2end/models/SqueezeNetNchw.cpp
- src/tests/end2end/models/SqueezeNetNhwc.cpp
When webnn_native gets built under .\third_party, the model paths
are incorrectly specified as always being relative to webnn_root (ex. ."\node\").
This PR specifies the model directory using an absolute path so the E2E tests can run under third_party/webnn_native without failure.
@huningxin @fujunwei
> Generate model paths for end2end tests at build.

- node/examples/electron/webnn-samples/forge.config.js
Remove whitespace between dirs as which would cause copying fail in app packaging.
> Fixed incorrect unpackDir expression

- node/examples/electron/webnn-samples/forge.config.js
Fix the Wasm file loading issue by copy the .wasm file to the root directory of the current demo. @Honry PTAL, thanks!
> [Sample] Fix load Wasm file issue of Rnnosie.

- .gitignore
- DEPS
- NOTICE
- README.md
- build_overrides/webnn_features.gni
- src/common/BUILD.gn
- src/webnn_native/BUILD.gn
- src/webnn_native/Operand.h
- src/webnn_native/WebnnNative.cpp
- src/webnn_native/mlas/ContextMLAS.cpp
- src/webnn_native/mlas/ContextMLAS.h
- src/webnn_native/mlas/GraphMLAS.cpp
- src/webnn_native/mlas/GraphMLAS.h
Support 11 ops including:
- conv2d (only nchw)
- pool2d (only nchw, average and max)
- add (only fused into conv2d)
- activations: clamp, relu, leakyRelu, sigmoid, exp, hardswish
- softmax
Depends on mlas of third_party/onnxruntime as one of DEPS.
fix #180
> [MLAS] add the initial implementation of MLAS backend

- src/common/BUILD.gn
WebNN's dawn_internal GN target was incorrectly scoped to to src/* which forbids examples/* targets from depending on it.
> Fix GN generation failure when building WebNN's common target from \\third_party.

- src/common/BUILD.gn
Clang has removed this flag and is no longer an option.
> Remove -Wreturn-std-move-in-c++11

- .github/workflows/build_test_dml.yml
- .github/workflows/build_test_node_dml.yml
- .github/workflows/build_test_node_openvino_linux.yml
- .github/workflows/build_test_node_openvino_windows.yml
- .github/workflows/build_test_null.yml
- .github/workflows/build_test_onednn_linux.yml
- .github/workflows/build_test_onednn_windows.yml
- .github/workflows/build_test_openvino_linux.yml
- .github/workflows/build_test_openvino_windows.yml
- DEPS
- README.md
This PR is
1. to introduce two conditions variables `checkout_polyfill` and `checkout_samples`, those **webnn-polyfill**(608M), **webnn-samples**(700M) and **test-data**(1.2G) dependencies repos would be checkout by default
2. to enable checkout **onnxruntime**(858M) dependency repo by default
Following table shows the checkout status in CI:
|CI \ Repo|webnn-polyfill (608M) + test-data(1.2G)|webnn-samples(700M) + test-data(1.2G)|onnxruntime (858M)|
|----|----|----|----|
|CI for null backend|NO|NO|NO|
|CI for DML/OpenVINO/oneDNN native backends|YES(1)|NO|NO|
|CI for WebNN-native Binding for node.js|YES|NO|NO|
|CI for MLAS backend _(TODO)_|YES(1)|NO|YES|
Note:
(1) Actually in CI for native backends, only test-data repo is required to checkout for testing End2End tests(model tests). …
> Fix the issue of no space in CI

- src/webnn_native/dml/GraphDML.cpp
Latest Clang does not allow re-declaring a local variable.
This fix simply removes the local variable declaration.
Fix #196
> Fix Graph::AddGemm from variable shadowing.

- DEPS
New allocation system. GPGMM is now O(1) and O(gpuPageSize) vs WebGPU/Dawn's O(Log2) and O(resourceHeapSize) for time and space complexity, respectively.
> Roll third_party/gpgmm/ 7c81fae56..c52956998 (157 commits)

- examples/MobileNetV2/Main.cpp
- examples/ResNet/Main.cpp
- examples/SampleUtils.cpp
- examples/SampleUtils.h
- examples/SqueezeNet/Main.cpp
- src/tests/End2EndTestsMain.cpp
- src/webnn_native/dml/GraphDML.cpp
- src/webnn_native/dml/deps/src/device.cpp
- src/webnn_native/dml/deps/src/device.h
- src/webnn_native/dml/deps/src/precomp.h
Enable setting power preference for selecting iGPU/dGPU on DML backend. Now you can choose iGpu/dGpu when running C++ examples and end2end tests under the webnn-native folder, for example:
iGpu: `out\Release\webnn_end2end_tests.exe --gtest_filter=*AddTests* -p low-power`
dGpu:` out\Release\webnn_end2end_tests.exe --gtest_filter=*AddTests* -p high-performance`
[Remarks](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_6/nf-dxgi1_6-idxgifactory6-enumadapterbygpupreference):
When DXGI_GPU_PREFERENCE_MINIMUM_POWER is specified for the GpuPreference parameter, the order of preference for the adapter returned in ppvAdapter will be:
1. iGPUs (integrated GPUs)
2. dGPUs (discrete GPUs)
3. xGPUs (external GPUs)
When DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE is specified for the GpuPreference …
> Support selecting iGPU/dGPU on DML backend

- DEPS
- src/webnn_native/dml/deps/src/device.cpp
GPGMM will ASSERT if device allocation leaks are present.
Roll third_party/gpgmm/ c52956998..1e5ae0071 (16 commits).
> Enable DML leak detection.

- .github/workflows/build_test_dml.yml
- .github/workflows/build_test_node_dml.yml
- DEPS
- src/webnn_native/dml/deps/src/device.cpp
New GPGMM capabilities:
* GPGMM will pre-fetch memory (on a background thread) automatically or by specifying `ALLOCATION_FLAG_ALWAYS_PREFETCH_MEMORY`. I noticed a 20-30% improvement in CPU time after this change.
* Added built-in allocation leak detection that is always enabled by default for debug builds. Because so, device based leak detection was moved behind a build flag.
* Memory is always recycled by default now, but you can disable this behavior by specifying `ALLOCATOR_FLAG_ALWAYS_ON_DEMAND` for troubleshooting out-of-memory (OOM) errors.
Enjoy WebNN team!
> Roll third_party/gpgmm/ 1e5ae0071..c5cd36d84 (181 commits)

- DEPS
- README.md
- src/tests/end2end/GemmTests.cpp
- src/tests/end2end/SplitTests.cpp
- src/webnn_native/BUILD.gn
- src/webnn_native/Instance.cpp
- src/webnn_native/WebnnNative.cpp
- src/webnn_native/xnnpack/BackendXNN.cpp
- src/webnn_native/xnnpack/BackendXNN.h
- src/webnn_native/xnnpack/ContextXNN.cpp
- src/webnn_native/xnnpack/GraphXNN.cpp
- src/webnn_native/xnnpack/GraphXNN.h
- webnn.json
XNNPACK subgraph API is used by [TFLite XNNPACK delegate](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/xnnpack) for graph level optimization and execution with good performance.
This PR updates WebNN-native's XNNPACK backend to support subgraph API with 27 ops support
* binary including add, sub, mul, div, max, min
* clamp
* concat (only support concatenation of up to 4 inputs)
* conv2d (only support nhwc layout)
* gemm (only support constant weights)
* matmul (only support 2d operand b)
* pad
* pool2d: average and max (only support nhwc layout)
* reshape
* split (only support even split up to 4 outputs)
* squeeze
* unary including abs, ceil, floor, neg
* activations: relu, leakyRelu, hardswish, sigmoid
* softmax
webnn_end2end_tests results:
[  PASSED  ] …
> XNNPACK backend supports subgraph API

- DEPS
- README.md
No regression of webnn_end2end_tests.
@fujunwei , PTAL.
@BruceDai , this PR is required to build XNNPACK with MSVC static runtime lib on Windows. Please also take a look.
Thanks.
> [XNNPACK] upgrade to support MSVC static runtime lib

- src/webnn_native/xnnpack/BackendXNN.cpp
- src/webnn_native/xnnpack/BackendXNN.h
- src/webnn_native/xnnpack/ContextXNN.cpp
- src/webnn_native/xnnpack/ContextXNN.h
The pthreadpool should be created per backend instead of per context. This PR fix it.
@fujunwei @Honry , PTAL. Thanks.
> [XNNPACK] create pthreadpool per backend

- src/webnn_native/dml/deps/src/device.h
Device held a raw reference to a returned ref-counted COM object which causes it to leak because Release() will never be automaically called upon device destruction.
This fixes the issue by making it use a COM reference instead, like other D3D12 created objects.
> Fix residency management leak when device destructs.

- src/webnn_native/NamedInputs.h
- src/webnn_native/NamedOutputs.h
- src/webnn_native/xnnpack/BackendXNN.cpp
- src/webnn_native/xnnpack/GraphXNN.cpp
- src/webnn_native/xnnpack/GraphXNN.h
Only call xnn_setup_runtime when any external pointers change and use unordered_map for inputs and outputs.
@fujunwei @Honry , PTAL. Thanks!
> [XNNPACK] optimize the compute performance

- src/webnn_native/BUILD.gn
- src/webnn_native/dml/deps/script/download_dml.py
With https://github.com/microsoft/DirectML/issues/234 fixed, we can upgrade DML to latest 1.8.2 version now. @huningxin @fujunwei @BruceDai
> Upgrade DirectML version to 1.8.2(latest)

- src/webnn_native/openvino/GraphIE.cpp
- third_party/openvino/ngraph_c_api/src/ngraph_c_api.cpp
- third_party/openvino/ngraph_c_api/src/ngraph_c_api.h
Add transpose parameters to `ngraph_mat_mul` function and map the transpose option of Gemm (WebNN) to the transpose parameters of MatMul (IE).
> [IE] Map the transpose option of Gemm to the parameters of MatMul.

- node/src/Context.cpp
- node/src/Context.h
- node/src/ML.cpp
- node/src/ML.h
There should be only one instance globally. Otherwise there will be duplicated allocations for per instance resources, e.g., the threadpool for XNNPACK backend.
@fujunwei @Honry PTAL. Thanks.
> [Node] avoid creating instance per context

- README.md
- build_overrides/webnn_features.gni
- src/webnn/common/BUILD.gn
- src/webnn/native/BUILD.gn
- src/webnn/native/Instance.cpp
- src/webnn/native/dml/BackendDML.cpp
- src/webnn/native/dml/BackendDML.h
- src/webnn/native/dml/ContextDML.cpp
- src/webnn/native/dml/ContextDML.h
- src/webnn/native/dml/DMLUtils.h
- src/webnn/native/dml/GraphDML.cpp
- src/webnn/native/dml/GraphDML.h
- webnn.json
Re-submit the new DML backend [PR](https://github.com/webmachinelearning/webnn-native/pull/242). 
1. DirectML.Debug.dll can be copied to the generated "out/*" path on DML/DMLX backend debug version to enable debug layer.
2. End2end cases of supported ops can pass as DirectMLX backend, no regression. 
3. ConvTranspose2d and Gru will be added after the PR merged. @miaobin 
4. Need to add the CI in another PR. Please also help open issue to track. Thanks! @BruceDai
5. Need to ensure that the chromium can run on this backend. (enable wire/gpu buffer), will open issue to track. @mingmingtasd 
PTAL again, thanks! @fujunwei
> Add a new dml backend

- DEPS
- build_overrides/gpgmm.gni
- src/webnn/native/dmlx/deps/src/util.h
Highlights:
* Heap recycling is now prioritized over pre-allocation when over budget.
* Heap re-sizing is now supported and enabled when under budget.
Breaking changes
* `ResourceAllocation::UpdateResidency` is now depreciated (replaced by `ResidencySet::Insert`).
Fixed:
* Program exit access violation due to trace recording being mistakenly enabled.
@fujunwei @fujunwei
> Roll third_party/gpgmm/ c32f9d37f..72f910e8d (229 commits)

- build_overrides/webnn_features.gni
- src/webnn/native/BUILD.gn
- src/webnn/native/dmlx/deps/src/device.cpp
How to collect:
1. Add `webnn_enable_resource_dump = true` to `args.gn`.
2. Run any executable (chrome.exe, end2end, etc).
3. Open `gpgmm_event_trace.json` in `chrome://tracing`.
How to analyze:
You basically want `GPU allocation utilization` to be **always 100%** and `GPU memory utilization` to be always **under 100%**. The former means NO allocation is being wasted and the latter means NO memory is being paged-out to the OS. `GPU memory free` reports waste due to fragmentation, this should be small.
How does it work:
GPGMM tracks how much actual resource memory was used. For example, if you create 1GB heap, that contains a 1 byte resource, this will correctly reported as 1B used. OS tools like WPA just report 1GB being used, not very helpful.
@fujunwei @mingmingtasd
> Enable GPU memory trace dump

- src/webnn/native/openvino/GraphIE.cpp
- src/webnn/native/ops/Reshape.cpp
- src/webnn/tests/end2end/ReshapeTests.cpp
Added test case for Reshape 0D tensor and fixed the related bug.
> Fixed memory error for empty values in GraphIE.cpp AddConstantWithGraph

- examples/SuperResolution/SuperResolution.cpp
- examples/SuperResolution/SuperResolution.h
- src/webnn/native/dmlx/GraphDMLX.cpp
- src/webnn/tests/BUILD.gn
- src/webnn/tests/end2end/models/SuperResolutionNchw.cpp
Adds SuperResolution to WebNN!
> Add SuperResolution example and test

- src/webnn/native/dmlx/GraphDMLX.cpp
- src/webnn/native/dmlx/deps/src/device.cpp
- src/webnn/native/dmlx/deps/src/device.h
Allows PIX to capture the DML backend for analysis.
> Enable PIX Capture for debug builds.

- .github/workflows/auto_roll_deps.yml
- .github/workflows/build_test_openvino_windows.yml
@fujunwei Last configured permissions setting of Auto rolling DEPS CI didn't work, so I removed these settings in this PR.
I just ping @anssiko to help manually configure that.
> Remove permissions settings in Auto roll CI by manually configuration.

- .github/workflows/build_mlas_windows.yml
- .github/workflows/build_test_dmlx.yml
- .github/workflows/build_test_onednn_linux.yml
- .github/workflows/build_test_onednn_windows.yml
- .github/workflows/build_test_openvino_linux.yml
- .github/workflows/build_test_openvino_windows.yml
- .github/workflows/build_test_xnnpack_linux.yml
- .github/workflows/build_test_xnnpack_windows.yml
- .github/workflows/memory_leak_check_dmlx.yml
Thanks for @anssiko's help of setting "Branch protection rules" for `main` branch, now we can see on PR #295, the `Build, Test OpenVINO (Windows)` CI was configured to check pass before merging auto generated PRs by [Auto rolling DEPS CI](https://github.com/webmachinelearning/webnn-native/actions/workflows/auto_roll_deps.yml). This's an experiment, since there're many decencies,  we need add more CIs to check those auto generated PRs.
> Add job names for checking to auto merge PRs by Auto rolling DEPS CI.

- .gitignore
`.gclient_previous_sync_commits` file of #295 should be ignored.
@anssiko @fujunwei PTAL, thanks.
> Ignore .gclient_previous_sync_commits file.

- DEPS
- build_overrides/webnn_features.gni
- src/webnn/native/BUILD.gn
- src/webnn/native/dmlx/deps/src/device.cpp
- src/webnn/native/dmlx/deps/src/device.h
Adds build option webnn_use_min_gpgmm, to build using the GPGMM minimum viable implementation (MVI). GPGMM MVI builds a self-contained source folder (src/include/min) which can be whole-copied into another source-tree. GPGMM MVI is a pass-through implementation of GPGMM. Please see /src/include/min/gpgmm_d3d12.h for limitations.
> Enable GPGMM without requiring DEPS.
